[project]
name = "academy-course-sfi32064"
version = "0.1.0"
description = "An introduction to Environmentally Extended Input-Output Economic Models using Python"
requires-python = ">=3.10"
dependencies = []
